version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-tender
    restart: always
    ports:
      - "27017:27017"  # Открываем порт для доступа к MongoDB (для разработки/тестирования)
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db  # Named volume для данных MongoDB

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
volumes:
  mongodb_data:
